name: mscanner
description: "mscanner by thj."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.10+89

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  http: ^1.2.2
  image_picker: ^1.1.2
  settings_ui: ^2.0.2
  geolocator: ^14.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.3.3
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  adaptive_theme: ^3.6.0
  url_launcher: ^6.3.1
  latlong2: ^0.9.1
  google_maps_flutter: ^2.12.1
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  flutter_image_compress: ^2.4.0
  share_plus: ^10.1.3
  getwidget: ^6.0.0
  html: ^0.15.4
  flutter_html: ^3.0.0
  cached_network_image: ^3.4.1
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6
  package_info_plus: ^8.1.2
  in_app_review: ^2.0.10
  fl_chart: ^0.70.2
  device_info_plus: ^11.3.3
  webview_flutter: ^4.10.0
  flutter_custom_tabs: ^2.2.1
  dart_geohash: ^2.1.0
  translator: ^1.0.3+1
  in_app_purchase: ^3.2.3
  provider: ^6.1.5
  image: ^4.5.4


dependency_overrides:
  google_maps_flutter_ios: 2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^5.5.2
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  flutter_lints: ^5.0.0
  intl_translation: ^0.20.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/home_icon.png
    - assets/images/camera_icon.png
    - assets/images/history_icon.png
    - assets/images/settings_icon.png
    - assets/images/logo.png
    - assets/images/
    - assets/.env
    - assets/map_styles/dark_mode.json
    - assets/images/help_icon_light.png
    - assets/images/help_icon_dark.png
    - assets/images/manual_dark.png
    - assets/images/manual_light.png
    - assets/images/tutorial_sample.jpg




    - assets/fonts/SF-Pro.ttf
    - assets/fonts/SF-Pro-Display-Bold.otf
    - assets/fonts/SF-Pro-Italic.ttf

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Italic.ttf
          style: italic
        - asset: assets/fonts/SF-Pro-text-black.otf